name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        min_allowed_lint_score_per_file=9.0
        
        echo "Min allowed score per file is $min_allowed_lint_score_per_file"
        for file in $(git ls-files '*.py')
        do
          echo "Linting `$file`"
          pylint "$file" --fail-under $min_allowed_lint_score_per_file
        done
